= About me
Duncan Dickinson 
2017-06-22
:jbake-type: page
:jbake-status: published

Welcome to my Notebooks site - a place for me to highlight some of the explorations I've undertaken. 

For many years I've tried out different technologies and setup 
"experiments" to see if/how something would work. As part of this work I usually document my approach
to help with organising my approach and to recall steps at a later date. I'll use this site to 
highlight activities I've undertaken. The tone is direct and does not aim to be a step-by-step guide.
The code is experimental and does not aim to provide a production-ready copy+paste solution.

I hope you find my posts useful.

[IMPORTANT]
.Content licence
====
All content is covered by a http://creativecommons.org/licenses/by/4.0/[CC-BY] licence 
unless explicitly stated otherwise.

If you need a specific code licence, I *should* have one in the repository but happily 
fall back to the https://opensource.org/licenses/BSD-2-Clause[BSD 2 Clause] licence if
I haven't. 
====

== Contact me

Connecting via my https://www.linkedin.com/in/dedickinson[LinkedIn] profile is your best bet 
if you'd like to drop me a line.

Many of the posts will link to the project repository - that's the best place to note issues or 
submit pull requests.

I used to pay more attention to Twitter but have found myself wandering away from the constant
stream. I'm not on Facebook or any other social media system.

== Other stuff

I have a few things floating around the web that may be of interest.

I wrote a couple of books:

* https://leanpub.com/groovytutorial[The Groovy 2 Tutorial] - a self-published introduction to Groovy
* https://www.syncfusion.com/resources/techportal/details/ebooks/groovy_succinctly[Groovy Succinctly] - further writings on Groovy

I do have an http://blog.duncan.dickinson.name/[old blog] that's not seen a lot of action.

== About this site

This site is built using:

- http://jbake.org[JBake] for generating the static site
- http://asciidoctor.org[Asciidoctor] for authoring content
- http://getbootstrap.com[Bootstrap] to make it look like I can do some stylish web stuff
- https://highlightjs.org[highlight.js] for code highlighting
- http://glyphicons.com/[Glyphicons] nifty icons
- http://fontawesome.io[Font Awesome] nifty icons